### ISSUE TITLE
Run code Error ：Can't find class

### ISSUE THREAD

**Issue by TimeCyber** [google/live-transcribe-speech-engine#1]
when i complier the project. In class AlwaysSameSpeakerIDLabeler and AlwaysSameSpeakerIDLabeler have an error.
show
package com.google.audio can't find class SpeakerIDInfo
![image](https://user-images.githubusercontent.com/9687149/63243660-d0c10a00-c28d-11e9-8bd1-47d3b1f951a9.png)

**Comment by chetgnegy-google** [comment]
Is there any other information that you can give us to help reproduce this? I'm happy to have someone on our team look into this.

We want the instructions in the README to work for any Linux system, and we don't guarantee that they'll work with some other kind of setup (or building without our scripts). Please let us know if you're trying something different.

**Comment by TimeCyber** [comment]
I use the android studio under windows, I found the SpeakerIdInfo.java code generated by the protocol buffer compiler, but automatically generate the Class SpeakerIdInfo's "D" to lowercase.
![image](https://user-images.githubusercontent.com/9687149/63996988-c45f6b80-cb2f-11e9-8a66-1e967327ef95.png)
![image](https://user-images.githubusercontent.com/9687149/63997140-32a42e00-cb30-11e9-8c73-62efada970c0.png)

**Comment by chetgnegy-google** [comment]
Thanks! Some folks on my team observed the same thing when they dug into this. I think they have a fix on the way.

**Comment by chetgnegy-google** [comment]
This should be fixed. Please verify.
