### ISSUE TITLE
Does this provide speaker identification?

### ISSUE THREAD

**Issue by JaveedSpritle** [google/live-transcribe-speech-engine#13]
Hey, i just want to know whether this library supports speaker identification.

**Comment by alextchuang-google** [comment]
Thank you for asking. We don't provide speaker identification implementation details in this project, instead we leave an interface to user to build it. Please refer AlwaysSameSpeakerIDLabeler.java.

https://github.com/google/live-transcribe-speech-engine/blob/master/app/src/main/java/com/google/audio/asr/RepeatingRecognitionSession.java#L674
