### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by baole** [google/live-transcribe-speech-engine#14]
I would like to integrate this project in to an app. I have a few questions regarding to this project:

- Do I need a Google cloud API key to make transcription work?
- As it works offline, do we pay for transcription?
- Does it support auto-language detection?

**Comment by alextchuang-google** [comment]
Sorry for the late response.

- Do I need a Google cloud API key to make transcription work?
Yes, please refer below link to create your API key.
https://cloud.google.com/docs/authentication/api-keys

- As it works offline, do we pay for transcription?
The live-transcribe-speech-engine project depends on cloud speech-to-text API which is an online service. We don't support offline mode.

- Does it support auto-language detection?
The beta version of cloud speech-to-text API supports this feature but please not it's only supported for Voice Command and Voice Search. See fields of alternativeLanguageCodes and model in RecognitionConfig for more details. So the answer is no, the model is one of default or video in [CloudSpeechSession](https://github.com/google/live-transcribe-speech-engine/blob/master/app/src/main/java/com/google/audio/asr/cloud/CloudSpeechSession.java#L242).
https://cloud.google.com/speech-to-text/docs/multiple-languages
https://cloud.google.com/speech-to-text/docs/reference/rest/v1p1beta1/RecognitionConfig
