### ISSUE TITLE
How to make it work on Windows?

### ISSUE THREAD

**Issue by kajalgupta26** [google/live-transcribe-speech-engine#15]
Hi,

I see that the cmake is for linux OS but I wanted to build it on Windows. Could you please help me in doing so as I am not able to build it.

**Comment by ausmuschang-google** [comment]
@kajalgupta26 ,
android sdk provide the build environment(includes cmake) for Windows but our script instructions were assumed run on linux system. If we plan to figure out for Windows and will update it.
