### ISSUE TITLE
Is it possible for the Live Transcribe Speech Engine to be used Chrome Extension?

### ISSUE THREAD

**Issue by Mctoodles-NNN** [google/live-transcribe-speech-engine#17]
Is it possible for the Live Transcribe Speech Engine to be used Chrome Extension for Windows 10?

**Comment by alextchuang-google** [comment]
Yes, it is possible. However the chrome extension are made up with web development technologies and a port of the code would be required to run on chrome extension. We hope our implementation will serve as guidance on how to port it to other languages.
