### ISSUE TITLE
Fatal error: ogg/ogg.h file not found

### ISSUE THREAD

**Issue by khaintt** [google/live-transcribe-speech-engine#18]
Hello,
I tried but could not build native library. Something went wrong with 

[build_log.txt](https://github.com/google/live-transcribe-speech-engine/files/4482341/build_log.txt)
`third_party/opus_tools/src/src/opus_header.h:31:10: fatal error: 'ogg/ogg.h' file not found` 

I attached build_log.txt, please take a look if you have time.

**Comment by ausmuschang-google** [comment]
Hi,
please have a trial [commit#9](https://github.com/google/live-transcribe-speech-engine/commit/d06ae837fee7cf2c117b150e9927b2eb082ad580)

**Comment by gokul-kumar96** [comment]
When I download the Project  and set up into my Android Studio the gradle files does not build  it shows the Error in Add Configuration and   am using the version of Android Studio 3.4.1 . In the DownLoaded File it contains the proto,third_party and i couldn't know whats the usuage for it. So  please give me some solutions.

**Comment by ausmuschang-google** [comment]
[commit#9](https://github.com/google/live-transcribe-speech-engine/commit/d06ae837fee7cf2c117b150e9927b2eb082ad580) is probably solved it so closed.

**Comment by tuan-jason** [comment]
@ausmuschang-google We still have this build error as of today.
Could you take a look into our build log here?

[build_log.txt](https://github.com/user-attachments/files/19642422/build_log.txt)
