### ISSUE TITLE
Ninja : Error

### ISSUE THREAD

**Issue by gokul-kumar96** [google/live-transcribe-speech-engine#19]
When i am running the project in android studio i got the error as :
Build command failed.
Error while executing process E:\Android\Studio\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\rajarajanayyarasu\Desktop\live-transcribe-speech-engine-master\live-transcribe-speech-engine-master\app\.externalNativeBuild\cmake\arm7Debug\armeabi-v7a --target ogg_opus_encoder_tool}

ninja: error: '../../../../third_party/libopus/lib/armeabi-v7a/libopus.a', needed by '../../../../build/intermediates/cmake/arm7/debug/obj/armeabi-v7a/libogg_opus_encoder_tool.so', missing and no known rule to make it
Please Give some solutions to fix it.I dont know how to fix it.

**Comment by ausmuschang-google** [comment]
hi, could you provide the "build_log.txt" for checking. Thanks.

**Comment by ausmuschang-google** [comment]
Hi,
The failed is related with build libraries out using our sample Android application.
Currently, these instructions assume that the host operating system is an Ubuntu-like flavor of Linux. For other operating systems likes as Window, we cannot promise that run well in other build environments.
However, it is an optional solution, you can refer attached patch file which striped out the native libs of compressing audio. 
You don't need to run build_all.sh to generate APK, instead you could build it by your android studio.
[0001-Remove-Opus-native-libs-for-windows.patch.zip](https://github.com/google/live-transcribe-speech-engine/files/4694237/0001-Remove-Opus-native-libs-for-windows.patch.zip)
