### ISSUE TITLE
Running on pc

### ISSUE THREAD

**Issue by Jochen-sys** [google/live-transcribe-speech-engine#21]
Does somebody know, how I can run the live-transcribe-speech-engine on a pc?
When someone has an idea, please tell me. Thanks!

**Comment by ausmuschang-google** [comment]
Interesting, what kind of develop program you prefer run on PC and what is the purpose?
Has a quick way, you can run the demo application in the emulator on Android studio. Ha.

**Comment by Jochen-sys** [comment]
When I ran it in Android Studio, it builds a mobile phone, but I want, that it looks like a normal Desktop App.

**Comment by ausmuschang-google** [comment]
Our implementation here is Android-specific. Our team regretfully does not have the resources to personally take on the responsibility of porting this to multiple other languages
or platforms.

Google's cloud team has provided examples on how to do this at the following link:
https://cloud.google.com/speech-to-text/docs/samples

these examples still show how to use the API and can be modified to be more similar to the Live Transcribe engine.
You can post a request to the Cloud team at one of the githubs linked above. If you generate evidence that our solution is more robust, you might persuade them to make such modifications.
