### ISSUE TITLE
Is NDK really needed here?

### ISSUE THREAD

**Issue by nicksav** [google/live-transcribe-speech-engine#22]
Hey guys,

We are thinking to get this into Flutter app and then into Google Glass EE2 and wonder how to make it happen.
A lot of road blocks we got - with NDK. Do we really need it in this app?

Correct me if I am wrong but all NDK usage is because of the extra codecs implementation? So, if we just remove all codecs code, we should make it work?

Thanks
Nick

**Comment by alextchuang-google** [comment]
Hi Nick,

NDK here is used to build libopus/libogg encoding, it's fine to remove it but I wanna mention that the expense of cloud service access would increase. We have a patch for this earlier, please refer to https://github.com/google/live-transcribe-speech-engine/issues/20#issuecomment-635200796.

Alex

**Comment by nicksav** [comment]
I am very sorry, but how to use that patch file?

Thanks
Nick

**Comment by alextchuang-google** [comment]
Sorry for late reply.

You can try the command git apply [PATCH_FILE] or refer to the code in the patch file and modify by yourself.
https://git-scm.com/docs/git-apply

**Comment by eladd** [comment]
Hi Alex,

Are you sure that using a flac audio (libopus/libogg encoding)  decrease the expense on Cloud Speech API? I didn't find any mentioned of this on GCP.

**Comment by nicksav** [comment]
btw, works like magic!

**Comment by alextchuang-google** [comment]
> Hi Alex,
> 
> Are you sure that using a flac audio (libopus/libogg encoding) decrease the expense on Cloud Speech API? I didn't find any mentioned of this on GCP.

Sorry for wrong words, should be network bandwidth, not the GCP expense.
