### ISSUE TITLE
Task :app:compileArm7DebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by DAVYSEN** [google/live-transcribe-speech-engine#3]
![image](https://user-images.githubusercontent.com/7521839/63251709-d83dde80-c2a0-11e9-93e8-db9e6396c73a.png)

**Comment by DAVYSEN** [comment]
![image](https://user-images.githubusercontent.com/7521839/63251869-3b2f7580-c2a1-11e9-92f9-7866bcfd0c3e.png)

**Comment by chetgnegy-google** [comment]
I think this is a duplicate issue of https://github.com/google/live-transcribe-speech-engine/issues/1. Let me know if you believe otherwise. Please see comments there.
