### ISSUE TITLE
Python implementation required

### ISSUE THREAD

**Issue by rayanfer32** [google/live-transcribe-speech-engine#5]
live dictation for python

**Comment by chetgnegy-google** [comment]
Thanks for the request! We acknowledge that the Android-specific nature of this codebase is a challenge for developers, but our team regretfully does not have the resources to personally take on the responsibility of porting this to multiple other languages or platforms.

Google's cloud team has provided examples on how to do this at the following link:
https://cloud.google.com/speech-to-text/docs/samples

While we personally feel that our implementation is more robust than these examples, these examples still show how to use the API and can be modified to be more similar to the Live Transcribe engine. You can post a request to the Cloud team at one of the githubs linked above. If you generate evidence that our solution is more robust, you might persuade them to make such modifications.

Finally, if you or someone else in the community happens to make a port of this library, I'm happy to put a link to it on this page.
