### ISSUE TITLE
here still has problem

### ISSUE THREAD

**Issue by TimeCyber** [google/live-transcribe-speech-engine#7]
Error: The class SpeakerIdInfoOrBuilder is public and should be declared in a file named SpeakerIdInfoOrBuilder. Java
and
Error: The class SpeakerIdInfois public and should be declared in a file named SpeakerIdInfo. Java

![image](https://user-images.githubusercontent.com/9687149/64949077-f9e3b300-d8aa-11e9-8087-fd0a5e13588a.png)

**Comment by alextchuang-google** [comment]
It looks like the same issue as https://github.com/google/live-transcribe-speech-engine/issues/1. May I know if your source code contains the fixed patch (https://github.com/google/live-transcribe-speech-engine/commit/bdf27f268c840bff1f91c89d129342fdf86948a6)?

If it still happens could you share your project configuration like gradle plugin version and gradle version?

**Comment by alextchuang-google** [comment]
Please verify. Feel free to reopen this if you still encounter the problem.
